/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.7.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { AnyDataModel } from "convex/server";
import type { GenericId } from "convex/values";

/**
 * No `schema.ts` file found, using `any` data model.
 *
 * To generate types for your tables, add a schema.ts file. You can start by
 * copying this template:
 *
 * ```ts
 * import { defineSchema, defineTable } from "convex/server";
 * import { v } from "convex/values";
 *
 * export default defineSchema({
 *   // Add your tables here, for example:
 *   // users: defineTable({
 *   //   name: v.string(),
 *   //   email: v.string(),
 *   // }).index("by_email", ["email"]),
 * });
 * ```
 *
 * The data model docs: https://docs.convex.dev/database/schemas#defining-a-schema
 */

/**
 * The names of all of your Convex tables.
 */
export type TableNames = "qrCodes" | "clicks";

/**
 * The type of a document stored in Convex.
 *
 * @typeParam TableName - A string literal type of the table name (like "users").
 */
export type Doc<TableName extends TableNames> = TableName extends "qrCodes"
  ? {
      _id: Id<"qrCodes">;
      _creationTime: number;
      name: string;
      targetUrl: string;
      shortId: string;
      qrDataUrl: string;
      createdAt: number;
    }
  : TableName extends "clicks"
    ? {
        _id: Id<"clicks">;
        _creationTime: number;
        qrCodeId: Id<"qrCodes">;
        timestamp: number;
        userAgent?: string;
        ipHash?: string;
      }
    : never;

/**
 * An identifier for a document in Convex.
 *
 * Convex documents are uniquely identified by their `Id`, which is accessible
 * on the `_id` field. To learn more, see [Document IDs](https://docs.convex.dev/using/document-ids).
 *
 * Documents can be loaded using `db.get(id)` in query and mutation functions.
 *
 * **Important**: Use `myId.toString()` to serialize Convex ids to a string.
 * `JSON.stringify(myId)` will not work.
 *
 * @typeParam TableName - A string literal type of the table name (like "users").
 */
export type Id<TableName extends TableNames = TableNames> = GenericId<TableName>;

/**
 * A type describing your Convex data model.
 *
 * This type includes information about what tables you have, the type of
 * documents stored in those tables, and the indexes defined on them.
 *
 * This type is used to parameterize methods like `queryGeneric` and
 * `mutationGeneric` to make them type-safe.
 */
export type DataModel = AnyDataModel;
