/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.7.
 * To regenerate, run `npx convex dev`.
 * @module
 */

export * from "convex/server";
